install: 
    - pip install -U tox-travis
    - pip install -U travis-sphinx
    - pip install recommonmark markdown
language: python
python:
    - 3.6
    - 3.5
    - 3.4
    - 2.7
script:
    tox
before_deploy:
    - pip install recommonmark markdown
    - pip install sphinx-markdown-tables
    - pip install sphinx_bootstrap_theme
    - pip install -r requirements.txt
    - pip install numpydoc
    - travis-sphinx --outdir='docs/_build' build --source=docs --nowarn
    - touch docs/_build/.nojekyll
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: docs/_build
    on:
      branch: master
      python: 3.5
