# Structure of the YAML is:
#
# Term:
#     - TestType: argument(s)
#     - TestType: argument(s)
#
# Below are the actual test settings for this dataset:
#
# http://dataset.inbo.be/dagvlinders-inbo-occurrences


# Other tests not covered here:
#
# - list all terms that were not tested
# - list all terms that are empty for all records
# - list grouped unique values: scientificName, taxonRank, ...


occurrenceID:
  empty: False

type:
  if:
    - basisOfRecord:
        allowed: [HumanObservation]
      allowed: [Event]
    - basisOfRecord:
        allowed: [PreservedSpecimen]
      allowed: [PhysicalObject]
    - basisOfRecord:
        allowed: [Occurrence]
      allowed: [Text]

language:
  allowed: [en]

license:
  allowed: ['http://creativecommons.org/publicdomain/zero/1.0/']

rightsHolder:
  allowed: [INBO] # Example of an institution specific test

accessRights:
  allowed: ['http://www.inbo.be/en/norms-for-data-use']

datasetID:
  allowed: ['http://doi.org/10.15468/njgbmh']

institutionCode:
  allowed: [INBO]

datasetName:
  allowed: [Vlinderdatabank - Butterflies in Flanders and the Brussels Capital Region, Belgium]

ownerInstitutionCode:
  allowed: [INBO, INBO/LB-BIM]

basisOfRecord:
  allowed: [HumanObservation, PreservedSpecimen, Occurrence]

informationWithheld:
  allowed: [see metadata]

dataGeneralizations:
  if:
    - decimalLongitude:
        empty: False
      allowed: [coordinates are generalized to centroid a 5x5km UTM grid]
    - decimalLongitude:
        empty: True
      allowed: ['']

dynamicProperties:
  type: json

recordedBy:
  delimitedvalues:
    delimiter: " | "
    regex: 'observerID:*'
    maxlength: 20

individualCount:
  type: integer
  min: 1
  max: 200

sex:
  delimitedvalues:
    delimiter: " | "
    allowed: [female, male]
    empty: True

lifeStage:
  allowed: [adult]

associatedReferences:
  type: url  #url?

samplingProtocol:
  allowed: [casual observation, fixed sampling location, monitoring, recorded from collection, recorded from literature]

samplingEffort:
  type: json
  empty: True
  # if:
  #   - samplingProtocol:
  #       allowed: [fixed sampling location]
  #     empty: False
  #   - samplingProtocol:
  #       empty: True
  #     empty: True

eventDate:
  dateformat: ['%Y-%m-%d', '%Y-%m', '%Y'] # No ranges defined
  mindate: 1830-01-01
  maxdate: 2014-10-20

verbatimEventDate:
  dateformat: ['%Y-%m-%d/%Y-%m-%d', '%Y-%m/%Y-%m', '%Y/%Y'] # Only accept ranges

# locationID

continent:
  allowed: [Europe]

countryCode:
  allowed: [BE]

stateProvince:
  allowed: [Antwerp, Brussels Capital Region, East Flanders, Flemish Brabant, Limburg, West Flanders]

#municipality:
#  listvalues: true

# verbatimLocality

verbatimCoordinates:
  regex: 31U*
  maxlength: 8
  minlength: 8

# verbatimLatitude:
#   min: ...
#   max: ...

# verbatimLongitude:
#   min: ...
#   max: ...

verbatimCoordinateSystem:
  if:
    - verbatimCoordinates:
        empty: False
      allowed: [UTM 5km] # [Belgian Lambert 72, UTM 5km]
    - verbatimCoordinates:
        empty: True
      allowed: ['']

verbatimSRS:
  if:
    - verbatimCoordinates:
        empty: False
      allowed: [WGS84] # [Belgian Datum 1972, ED50, WGS84]
    - verbatimCoordinates:
        empty: True
      allowed: ['']

decimalLatitude:
  type: float
  numberformat: '.5'
  min: 50.68
  max: 51.51

decimalLongitude:
  if:
    decimalLatitude:
      empty: False
    empty: False
  if:
    decimalLatitude:
      empty: True
    allowed: ['']
  type: float
  numberformat: '.5'
  min: 2.54
  max: 5.92

geodeticDatum:
  if:
    decimalLongitude:
      empty: False
    allowed: [WGS84]
  if:
    decimalLatitude:
      empty: True
    allowed: ['']

coordinateUncertaintyInMeters:
  if:
    decimalLongitude:
      empty: False
    allowed: [3769] # Or use a range
  if:
    decimalLatitude:
      empty: True
    allowed: ['']

georeferenceRemarks:
  if:
    decimalLongitude:
      empty: False
    allowed: [coordinates are centroid of used grid square]
  if:
    decimalLatitude:
      empty: True
    allowed: ['']

identifiedBy:
  delimitedvalues:
    delimiter: " | "
    type: string

scientificName:
    empty: False

kingdom:
  allowed: [Animalia]

phylum:
  allowed: [Arthropoda]

class:
  allowed: [Insecta]

order:
  allowed: [Lepidoptera]

taxonRank:
  allowed: [species] # [species, subspecies, form]

scientificNameAuthorship:
  empty: false

vernacularName:
  if:
    taxonRank:
      allowed: [subspecies]
    empty: True

nomenclaturalCode:
  allowed: [ICZN] # [ICZN, ICBN]
